#!/usr/bin/python

import urllib, json, sys

text = urllib.urlopen('http://blockchain.info/latestblock').read()

try:
    jsonobj = json.loads(text)
    print jsonobj["height"]
except:
    sys.stderr.write("Bad JSON")
    sys.exit(-1)
