#!/usr/bin/python

import urllib, sys, urllib2

if len(sys.argv) < 2: 
    print "Need TX argument"
    sys.exit()

if sys.argv[1] == "-":
    txdata = sys.stdin.read().strip()
else:
    txdata = open(sys.argv[1]).read().strip()

url = 'http://blockchain.info/pushtx'
form_data = {'tx': txdata }
params = urllib.urlencode(form_data)
try:
    response = urllib2.urlopen(url, params)
    data = response.read()
except Exception, e:
    data = e.read().strip()

print data
