#!/usr/bin/python
import urllib, urllib2, sys, json, copy, random

opener = urllib2.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0'+str(random.randrange(1000000)))]

try:
    data = opener.open('http://blockchain.info/tx/%s?format=json' % sys.argv[1]).read()
    j = json.loads(data)
    print "true"
except:
    print "false"
