#!/usr/bin/python
import os
import obelisk

secret = os.urandom(32)
print "Secret:", secret.encode("hex")

d = obelisk.string_to_number(secret)
G = obelisk.generator_secp256k1
Q = d * G
pubkey = obelisk.get_point_pubkey(Q, True)
prefix = "\x00" * 5
assert len(prefix) == 5
version = chr(6)
address_data = version + pubkey + prefix
assert len(address_data) == 1 + 33 + 5
address = obelisk.EncodeBase58Check(address_data)
print "Address:", address

