#!/usr/bin/python
import obelisk
import hashlib
import sys

def initiate_stealth(pubkey):
    encode_key = obelisk.EllipticCurveKey()
    encode_key.new_key_pair()
    S1 = obelisk.diffie_hellman(encode_key.secret, pubkey)
    # Start the second stage.
    c = hashlib.sha256(S1).digest()
    nonce = encode_key.public_key
    # Now generate address
    point = obelisk.point_add(pubkey, c)
    addr_pubkey = obelisk.get_point_pubkey(point, True)
    address = obelisk.public_key_to_bc_address(addr_pubkey)
    return nonce.encode("hex"), address

def main(argv):
    if len(argv) != 2:
        print >> sys.stderr, "sx stealth-send ADDRESS"
        return -1
    address = argv[1]
    address_data = obelisk.DecodeBase58Check(address)
    if address_data is None or len(address_data) != 1 + 33 + 5:
        print >> sys.stderr, "sx: Incorrect stealth address."
        return -2
    pubkey = address_data[1:34]
    assert len(pubkey) == 33
    if pubkey[0] != "\x02" and pubkey[0] != "\x03":
        print >> sys.stderr, "sx: Invalid pubkey in stealth address."
        return -2
    # Start the process...
    ephemkey, address = initiate_stealth(pubkey)
    print "Emphemeral pubkey:", ephemkey
    print "Address:", address
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))

